import Link from 'next/link'
import Image from 'next/image'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of Use',
  description: 'Terms of use for Safety Margin — a free financial protection educational tool for Filipinos.',
  alternates: { canonical: '/terms' },
}

const CONTACT_EMAIL = 'support@safetymargin.app'

export default function TermsPage() {
  return (
    <main className="relative min-h-screen flex flex-col bg-navy-gradient">
      {/* Header */}
      <header className="relative z-10 flex items-center justify-between px-6 py-6 md:px-12 border-b border-white/5">
        <Link href="/" className="flex items-center gap-2.5">
          <Image src="/logo.png" alt="Safety Margin" width={36} height={36} className="object-contain" />
          <span className="font-sans text-sm text-white/60 tracking-widest uppercase">
            Safety Margin
          </span>
        </Link>
        <nav className="hidden sm:flex items-center gap-6">
          <Link href="/privacy" className="font-sans text-xs text-white/30 hover:text-white/60 transition-colors">Privacy Policy</Link>
          <Link href="/data-deletion" className="font-sans text-xs text-white/30 hover:text-white/60 transition-colors">Data Deletion</Link>
        </nav>
      </header>

      {/* Content */}
      <section className="relative z-10 flex-1 px-6 py-16 md:px-12">
        <div className="max-w-2xl mx-auto space-y-10">

          <div className="space-y-3">
            <p className="font-sans text-xs text-gold/70 tracking-widest uppercase">Last updated: June 4, 2026</p>
            <h1 className="font-serif text-4xl md:text-5xl text-white leading-tight">
              Terms of Use
            </h1>
            <p className="font-sans text-white/60 text-lg leading-relaxed">
              Please read these Terms of Use carefully before using Safety Margin.
              By accessing or using this tool, you agree to be bound by these terms.
            </p>
          </div>

          <hr className="border-white/10" />

          <div className="space-y-8 font-sans text-white/70 leading-relaxed">

            <section className="space-y-3">
              <h2 className="font-serif text-xl text-white">1. About this tool</h2>
              <p>
                Safety Margin is a <span className="text-white">free educational tool</span> operated by
                Jojo Cruzado, a licensed insurance advisor. The tool is designed to help Filipinos understand their financial
                protection gaps through a short quiz and AI-generated analysis.
              </p>
              <p>
                This tool is an independent personal platform and is not affiliated with any insurance company.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="font-serif text-xl text-white">2. Educational purpose only — not financial advice</h2>
              <div className="bg-gold/5 border border-gold/20 rounded-xl px-5 py-4 space-y-2">
                <p className="text-white/80 text-sm font-semibold">Important disclaimer</p>
                <p className="text-sm">
                  The Financial Protection Report generated by this tool is for <strong className="text-white">educational and informational
                  purposes only</strong>. It does not constitute financial advice, investment advice, insurance advice,
                  or any form of professional recommendation.
                </p>
              </div>
              <p>
                The AI-generated report is based solely on your multiple-choice answers and does not account for
                your complete financial situation, tax circumstances, legal status, or individual needs.
                Results should not be relied upon as the sole basis for any financial or insurance decision.
              </p>
              <p>
                Product suitability, coverage eligibility, premium amounts, and all insurance terms must be
                validated through an official proposal and consultation with a licensed advisor.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="font-serif text-xl text-white">3. Accuracy of AI-generated content</h2>
              <p>
                The Financial Protection Report is generated using artificial intelligence (OpenAI GPT-4o mini).
                While we strive for accuracy and relevance, AI-generated content may contain errors, omissions,
                or outdated information. We make no representations or warranties, express or implied, as to
                the accuracy, completeness, or fitness for a particular purpose of the generated report.
              </p>
              <p>
                Scores, labels, and recommendations are illustrative estimates based on general patterns and
                should be treated as a starting point for conversation — not a definitive assessment.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="font-serif text-xl text-white">4. Eligibility</h2>
              <p>
                This tool is intended for individuals who are at least <span className="text-white">18 years of age</span> and
                are residents or citizens of the Philippines. By using this tool, you represent that you
                meet these requirements.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="font-serif text-xl text-white">5. Your information and consent</h2>
              <p>
                By submitting your information through this tool, you consent to:
              </p>
              <ul className="list-disc list-inside space-y-1.5 pl-2 text-white/60 text-sm">
                <li>The collection and processing of your personal data as described in our <Link href="/privacy" className="text-gold underline underline-offset-2">Privacy Policy</Link></li>
                <li>Being contacted by Jojo Cruzado via mobile or email to discuss your results and financial protection options</li>
                <li>Receiving follow-up educational emails related to financial protection (you may unsubscribe at any time)</li>
              </ul>
              <p className="text-sm text-white/50">
                You may withdraw this consent at any time by emailing us at{' '}
                <a href={`mailto:${CONTACT_EMAIL}`} className="text-gold underline underline-offset-2">{CONTACT_EMAIL}</a>.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="font-serif text-xl text-white">6. Acceptable use</h2>
              <p>You agree not to:</p>
              <ul className="list-disc list-inside space-y-1 pl-2 text-white/60 text-sm">
                <li>Submit false, misleading, or fraudulent information</li>
                <li>Attempt to reverse-engineer, scrape, or automate submissions</li>
                <li>Use this tool for any purpose other than personal educational use</li>
                <li>Reproduce or redistribute the AI-generated report content for commercial purposes</li>
                <li>Attempt to circumvent any security measure or access restriction</li>
              </ul>
            </section>

            <section className="space-y-3">
              <h2 className="font-serif text-xl text-white">7. Intellectual property</h2>
              <p>
                All content, design, and code of this tool — including but not limited to the quiz questions,
                report format, visual design, and brand elements — is the property of Jojo Cruzado and
                Safety Margin. No portion may be reproduced or used without express written permission,
                except for personal, non-commercial use.
              </p>
              <p>
                Your AI-generated report is produced specifically for you. You may share it for personal
                purposes, but you may not reproduce it for commercial gain or misrepresent it as independent
                financial advice.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="font-serif text-xl text-white">8. Limitation of liability</h2>
              <p>
                To the fullest extent permitted by applicable law, Jojo Cruzado and Safety Margin
                shall not be liable for any direct, indirect, incidental, special, or consequential damages
                arising from your use of, or reliance on, this tool or the generated report.
              </p>
              <p>
                This tool is provided "as is" without warranties of any kind. We do not guarantee that the
                tool will be available, error-free, or uninterrupted at all times.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="font-serif text-xl text-white">9. Third-party links</h2>
              <p>
                This tool may contain links to third-party services (e.g. Calendly for booking, Facebook
                Messenger for contact). These are provided for convenience only. We have no control over
                and accept no responsibility for the content or privacy practices of any linked third-party site.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="font-serif text-xl text-white">10. Governing law</h2>
              <p>
                These Terms of Use shall be governed by and construed in accordance with the laws of
                the Republic of the Philippines, including the Data Privacy Act of 2012 (RA 10173),
                the Electronic Commerce Act (RA 8792), and other applicable regulations. Any disputes
                shall be subject to the exclusive jurisdiction of the courts of the Philippines.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="font-serif text-xl text-white">11. Changes to these terms</h2>
              <p>
                We reserve the right to update these Terms of Use at any time. Material changes will be
                indicated by an updated "Last updated" date. Your continued use of the tool after any
                change constitutes your acceptance of the revised terms.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="font-serif text-xl text-white">12. Contact</h2>
              <p>
                For questions about these terms, contact:
              </p>
              <div className="bg-navy-card border border-white/5 rounded-xl p-4 space-y-1 text-sm">
                <p className="text-white/80 font-semibold">Jojo Cruzado</p>
                <p className="text-white/50">Licensed Insurance Advisor</p>
                <a href={`mailto:${CONTACT_EMAIL}`} className="text-gold underline underline-offset-2 hover:text-gold-soft transition-colors">
                  {CONTACT_EMAIL}
                </a>
              </div>
            </section>

          </div>

          <hr className="border-white/10" />

          <div className="flex flex-wrap justify-center gap-6 text-sm">
            <Link href="/privacy" className="font-sans text-white/40 hover:text-gold transition-colors">
              Privacy Policy
            </Link>
            <Link href="/data-deletion" className="font-sans text-white/40 hover:text-gold transition-colors">
              Data Deletion Policy
            </Link>
            <Link href="/" className="font-sans text-white/40 hover:text-white/70 transition-colors">
              ← Back to Safety Margin
            </Link>
          </div>

        </div>
      </section>
    </main>
  )
}
